// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6sxkA30C2Rs9VVYGj8qOWWiVTDM4IUGk',
    appId: '1:856593740943:web:0438a21953b341f7e32cfa',
    messagingSenderId: '856593740943',
    projectId: 'warta-46528',
    authDomain: 'warta-46528.firebaseapp.com',
    storageBucket: 'warta-46528.firebasestorage.app',
    measurementId: 'G-230WGEL2KG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXrhb4pqmrsPf7LUkaPPVHXwnxMSpEKgo',
    appId: '1:856593740943:android:3116ab9eb5cb467ae32cfa',
    messagingSenderId: '856593740943',
    projectId: 'warta-46528',
    storageBucket: 'warta-46528.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_ukeloBAQvzskhILxPJ_a0lkPoI9bnGQ',
    appId: '1:856593740943:ios:92cf73cd6056919ae32cfa',
    messagingSenderId: '856593740943',
    projectId: 'warta-46528',
    storageBucket: 'warta-46528.firebasestorage.app',
    iosBundleId: 'com.example.wartaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_ukeloBAQvzskhILxPJ_a0lkPoI9bnGQ',
    appId: '1:856593740943:ios:92cf73cd6056919ae32cfa',
    messagingSenderId: '856593740943',
    projectId: 'warta-46528',
    storageBucket: 'warta-46528.firebasestorage.app',
    iosBundleId: 'com.example.wartaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6sxkA30C2Rs9VVYGj8qOWWiVTDM4IUGk',
    appId: '1:856593740943:web:07a35693f80ed19de32cfa',
    messagingSenderId: '856593740943',
    projectId: 'warta-46528',
    authDomain: 'warta-46528.firebaseapp.com',
    storageBucket: 'warta-46528.firebasestorage.app',
    measurementId: 'G-7WPVVHDZ8G',
  );
}
