-dontwarn com.google.mlkit.vision.text.chinese.**
-dontwarn com.google.mlkit.vision.text.devanagari.**
-dontwarn com.google.mlkit.vision.text.japanese.**
-dontwarn com.google.mlkit.vision.text.korean.**
-dontwarn com.google.mlkit.vision.text.thai.**
-dontwarn com.google.mlkit.vision.text.bengali.**
-dontwarn com.google.mlkit.vision.text.cjk.**
-dontwarn com.google.mlkit.vision.text.latin.**

-keep class com.google.mlkit.** { *; }
-keep class org.tensorflow.** { *; }